# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    filter_sets:
        thumb:
            quality: 80
            filters:
                thumbnail:
                    size: [350, 230]
                    mode: outbound
                    allow_upscale: true
                    allow_downscale: true
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound

        icon:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 30]
                    mode: outbound

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
