vich_uploader:
    db_driver: orm

    mappings:
        wine_image:
            uri_prefix: /images/wines
            upload_destination: '%kernel.project_dir%/public/images/wines'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
